#!/usr/bin/env node
// Emit the existing homepage cards into HTML using the same catalog and renderer
// as the browser. The page remains fully static; no server-side renderer needed.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { readToolCatalog } from './site-catalog.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const file = path.join(root, 'index.html');
const html = fs.readFileSync(file, 'utf8');
const catalog = readToolCatalog(html);
const renderer = html.match(/function toolCardHTML\(t\) \{[\s\S]*?\n  \}/)?.[0];
if (!renderer) throw new Error('Homepage renderer changed; update prerender-home.mjs.');
// Only execute these two known sections of our checked-in page, never remote HTML.
const { cards, count } = vm.runInNewContext(`
  const liveTools = ${JSON.stringify(catalog)};
  const favorites = [];
  ${renderer}
  ({ cards: liveTools.map(toolCardHTML).join(''), count: liveTools.length });
`, {}, { timeout: 1000 });
const marker = '<div class="featured-grid" id="featuredGrid">';
const start = html.indexOf(marker);
const endMarker = '\n    <div class="ad-slot ad-incontent">';
const end = html.indexOf(endMarker, start);
if (start < 0 || end < 0) throw new Error('Cannot find homepage grid boundaries.');
const cleanCards = cards.replace(/[\t ]+$/gm, '');
const next = (html.slice(0, start) + marker + '\n<!-- Generated by npm run prerender:home -->' + cleanCards + '\n    </div>' + html.slice(end))
  .replace(/(<span class="section-count-badge" id="toolCountBadge">)[^<]*(<\/span>)/, `$1${count} tools$2`);
if (process.argv.includes('--check')) {
  if (html !== next) throw new Error('Static homepage cards are stale. Run npm run prerender:home.');
} else if (html !== next) {
  fs.writeFileSync(file, next);
}
console.log(`Homepage contains ${count} static tool cards.`);
