/** ToolShoppy — static config for trends SEO automation */

export const TOOL_PATHS = {
  'word-to-pdf': '/tools/pdf/word-to-pdf/',
  'pdf-to-word': '/tools/pdf/pdf-to-word/',
  'pdf-compress': '/tools/pdf/compress/',
  'pdf-editor': '/tools/pdf/editor/',
  'pdf-merge': '/tools/pdf/merge/',
  'pdf-split': '/tools/pdf/split/',
  'unlock-pdf': '/tools/pdf/unlock/',
  'image-to-pdf': '/tools/pdf/image-to-pdf/',
  'pdf-to-image': '/tools/pdf/pdf-to-image/',
  'pdf-password-protect': '/tools/pdf/protect/',
  'image-compressor': '/tools/image/compress/',
  'image-converter': '/tools/image/convert/',
  'image-resizer': '/tools/image/resize/',
  'background-remove': '/tools/image/background-remove/',
  'image-upscale': '/tools/image/upscale/',
  'govt-photo-resizer': '/tools/image/govt-photo/',
  'passport-photo': '/tools/image/passport-photo/',
  'video-compress': '/tools/video/compress/',
  'video-trim': '/tools/video/trim/',
  'video-to-mp3': '/tools/video/to-audio/',
  'status-splitter': '/tools/video/status-splitter/',
  'qr-generator': '/tools/misc/qr-generator/',
  'gold-rate': '/tools/rates/gold-rate/',
  'silver-rate': '/tools/rates/silver-rate/',
  'currency-converter': '/tools/rates/currency-converter/',
  'petrol-price': '/tools/rates/petrol-price/',
  'audio-cutter': '/tools/misc/audio-cutter/',
};

/** Queries we never map (news, brands without tools, etc.) */
export const NOISE_PATTERNS = [
  /^microsoft word$/,
  /^google doc?s?$/,
  /^wikipedia$/,
  /^walmart/,
  /^openai/,
  /^new york times$/,
  /^iran news$/,
  /^uae news/,
  /^emirates$/,
  /^noon$/,
  /^amazon uae$/,
  /^make my trip$/,
  /^sensex/,
  /^nifty/,
  /^bitcoin price/,
  /^whatsapp login$/,
  /^online games$/,
  /^canva$/,
  /^adobe acrobat$/,
  /^adobe express$/,
  /^smallpdf$/,
  /^small pdf$/,
  /^lightpdf$/,
  /^light pdf$/,
  /^capcut$/,
  /^handbrake$/,
  /^ffmpeg$/,
  /^7-zip$/,
  /^wetransfer$/,
  /^dropbox$/,
  /^google drive$/,
  /^drive$/,
  /^nvsp$/,
  /^rtps$/,
  /^csc$/,
  /^uidai$/,
  /^aadhar card download$/,
  /^compression socks$/,
  /^what is a (swap|json|midi|zip) file/,
  /^how (does|file compression)/,
  /^lossy vs lossless/,
  /^compression ratio$/,
  /^lidl near me$/,
];

/** First matching rule wins */
export const MAP_RULES = [
  { tool: 'pdf-editor', test: /pdf editor|editor pdf|editor de pdf|pdfescape|pdfgear|pdf gear|pdf free editor|free pdf editor|online pdf editor|pdf online editor|foxit pdf editor|easy online pdf editor|pdf text editor/ },
  { tool: 'word-to-pdf', test: /word to pdf|word file to pdf|from word to pdf|docx to pdf|doc to pdf|convert word to pdf|word to pdf converter|ilovepdf word to pdf|ilove word to pdf|i love pdf word to pdf|word to pdf i love pdf/ },
  { tool: 'pdf-to-word', test: /pdf to word|pdf to doc|from pdf to word|change pdf to word|convert pdf to word|pdf to word convert|free pdf to word|pdf to ms word|ubah pdf to word|ilovepdf pdf to word|i love pdf to word|love pdf to word|pdf to word i love pdf|i love my pdf to word/ },
  { tool: 'pdf-compress', test: /pdf file compression|compression pdf|pdf compression|pdf compression online|reduce pdf file size|compress pdf|free pdf compression|pdf compressor|free pdf compressor/ },
  { tool: 'video-compress', test: /video compressor|compressor de video|compress video|video size compressor|video file compressor|free video compressor|best video compressor|online video compressor|video quality compressor|video compressor to 10mb|video com$|large video compressor|video compressor download|video compressor app|video compressor software|clideo|kapwing|veed|panda video|proton video compressor|freeconvert/ },
  { tool: 'video-to-mp3', test: /video to audio|video to mp3/ },
  { tool: 'video-trim', test: /video trim|video cutter|trim video/ },
  { tool: 'image-compressor', test: /image compressor|photo compressor|image compression|png compression|jpeg compression|compress image|image kb converter|kb converter/ },
  { tool: 'image-to-pdf', test: /image to\.pdf|image to pdf|photo to pdf|free image to pdf/ },
  { tool: 'pdf-to-image', test: /pdf to image|pdf image converter|pdf to image converter|image to\.pdf converter/ },
  { tool: 'image-converter', test: /(?<!pdf )image converter|free image converter|heic to jpg|image to jpg|image to png|svg converter|image to video converter|image to link converter|image to base64|image to excel converter|image to vector|image to dxf|image to dwg|image ratio converter|4k image converter|hd image converter|low to high.*image converter|300x300 image converter|3000x3000 image converter|minecraft image converter|enhance image|jpg to jpeg converter/ },
  { tool: 'image-upscale', test: /image upscaler|upscale image|hd converter image|image hd converter|image to hd|4k converter image/ },
  { tool: 'pdf-merge', test: /merge pdf|pdf merge|pdf merger/ },
  { tool: 'pdf-split', test: /split pdf|pdf split/ },
  { tool: 'unlock-pdf', test: /unlock pdf|remove pdf password/ },
  { tool: 'pdf-password-protect', test: /password protect pdf|protect pdf|encrypt pdf/ },
  { tool: 'background-remove', test: /remove background|background remover/ },
  { tool: 'qr-generator', test: /qr code generator|qrcode monkey|qr code generator|text to qr|url to qr|wifi qr|vcard qr|whatsapp qr|pdf to qr|pdf qr|bulk qr|dynamic qr|static qr|custom qr|bar code generator|link to qr|link qr|monkey qr|me qr|uitly\.com.*qr/ },
  { tool: 'gold-rate', test: /gold (price|rate).*uae|gold (price|rate).*dubai|gold (price|rate).*india|gold rate|uae gold|today gold|24k gold|22k gold|gold price today|rate of gold|current gold rate|live gold rate|gold price uae|gold price in pakistan|one gram gold|1 gram gold|gold rate trend|gold price$/ },
  { tool: 'silver-rate', test: /silver (rate|price).*uae|silver (rate|price).*india|silver rate today|silver price today/ },
  { tool: 'currency-converter', test: /currency converter|currency exchange|xe currency|usd to inr|aed to inr|exchange rate.*inr|exchange rate uae|currency converter aed|currency converter uae|currency converter dubai|currency converter sar|currency converter kwd|currency converter omr|currency converter usd|currency converter eur|currency converter aud|currency converter gbp|currency converter near me|foreign currency|international currency|live currency|historical currency|mastercard currency|wise currency|visa currency|western union currency|hsbc currency|royal bank currency|cib currency|ecb currency|all currency|universal currency|currency exchange rate|tarkov currency|mtg currency/ },
  { tool: 'petrol-price', test: /petrol price|diesel price|fuel price|gas price today/ },
  { tool: 'govt-photo-resizer', test: /psc photo|upsc photo|pan card photo|aadhaar photo|govt photo|government photo|passport photo size/ },
  { tool: 'passport-photo', test: /passport photo|passport size photo/ },
  { tool: 'audio-cutter', test: /audio cutter|audio trim|ringtone maker|mp3 cutter/ },
  { tool: 'image-resizer', test: /image resizer|resize image|image resize/ },
];

/**
 * SEO landing / vanity redirect config.
 *
 * redirectOnly:true  — thin doorway URLs (.../free-online/, .../online/). No HTML is
 *   generated; vanity slug + legacy path both 301 to TOOL_PATHS[tool].
 * redirectOnly:false — programmatic location pages that still get a landing HTML.
 */
export const LANDING_PAGES = [
  {
    id: 'pdf-editor-free',
    path: '/tools/pdf/editor/free-online/',
    tool: 'pdf-editor',
    redirectSlug: 'free-online-pdf-editor',
    redirectOnly: true,
  },
  {
    id: 'word-to-pdf-free',
    path: '/tools/pdf/word-to-pdf/free-online/',
    tool: 'word-to-pdf',
    redirectSlug: 'word-to-pdf-free',
    redirectOnly: true,
  },
  {
    id: 'pdf-to-word-free',
    path: '/tools/pdf/pdf-to-word/free-online/',
    tool: 'pdf-to-word',
    redirectSlug: 'pdf-to-word-free',
    redirectOnly: true,
  },
  {
    id: 'pdf-compress-online',
    path: '/tools/pdf/compress/online/',
    tool: 'pdf-compress',
    redirectSlug: 'pdf-compression-online',
    redirectOnly: true,
  },
  {
    id: 'video-compress-free',
    path: '/tools/video/compress/free-online/',
    tool: 'video-compress',
    redirectSlug: 'free-video-compressor',
    redirectOnly: true,
  },
  {
    id: 'image-compress-free',
    path: '/tools/image/compress/free-online/',
    tool: 'image-compressor',
    redirectSlug: 'image-compressor-free',
    redirectOnly: true,
  },
  {
    id: 'image-to-pdf-free',
    path: '/tools/pdf/image-to-pdf/free-online/',
    tool: 'image-to-pdf',
    redirectSlug: 'image-to-pdf-free',
    redirectOnly: true,
  },
  {
    id: 'pdf-to-image-free',
    path: '/tools/pdf/pdf-to-image/free-online/',
    tool: 'pdf-to-image',
    redirectSlug: 'pdf-to-image-free',
    redirectOnly: true,
  },
  {
    id: 'image-converter-free',
    path: '/tools/image/convert/free-online/',
    tool: 'image-converter',
    redirectSlug: 'free-image-converter',
    redirectOnly: true,
  },
  {
    id: 'qr-generator-free',
    path: '/tools/misc/qr-generator/free-online/',
    tool: 'qr-generator',
    redirectSlug: 'free-qr-code-generator',
    redirectOnly: true,
  },
  {
    id: 'background-remove-free',
    path: '/tools/image/background-remove/free-online/',
    tool: 'background-remove',
    redirectSlug: 'remove-background-free',
    redirectOnly: true,
  },
  {
    id: 'currency-aed-inr',
    path: '/tools/rates/currency-converter/aed-inr/',
    tool: 'currency-converter',
    icon: 'currency-dollar',
    h1: 'AED to INR Currency Converter',
    sub: 'UAE Dirham to Indian Rupee — Gulf to India.',
    title: 'AED to INR Currency Converter — Live Rate | ToolShoppy',
    desc: 'Currency converter AED to INR. Live indicative rate for UAE to India remittances.',
    body: '<strong>Currency converter AED to INR</strong> is a top Gulf-India search. Check indicative rates before remitting.',
    redirectSlug: 'aed-to-inr',
    priority: 0.9,
  },
  {
    id: 'silver-rate-uae',
    path: '/tools/rates/silver-rate/uae/',
    tool: 'silver-rate',
    icon: 'coin',
    h1: 'UAE Silver Rate Today',
    sub: 'Silver price in UAE — updated daily.',
    title: 'UAE Silver Rate Today — Per Gram | ToolShoppy',
    desc: 'Silver rate in UAE today per gram. Free, no signup — alongside gold rates.',
    body: '<strong>Silver rate in UAE</strong> searches surged in recent Google Trends data. Check silver price per gram.',
    redirectSlug: 'silver-rate-uae',
    priority: 0.88,
  },
  {
    id: 'gold-rate-uae',
    path: '/tools/rates/gold-rate/dubai/',
    tool: 'gold-rate',
    icon: 'coin',
    h1: 'UAE Gold Rate Today',
    sub: 'Gold price in Dubai and UAE — updated daily.',
    title: 'UAE Gold Rate Today — 22K and 24K Per Gram | ToolShoppy',
    desc: 'Gold rate in UAE today. 22K and 24K per gram in Dubai — free, no signup.',
    body: '<strong>Gold rate in UAE</strong> is one of the fastest-rising searches in the Gulf. Check today\'s 22K and 24K rates.',
    redirectSlug: 'uae-gold-rate',
    priority: 0.92,
  },
];
